substitutions:
  _IMAGE: us-east4-docker.pkg.dev/manto-sagrado-lhg/manto-sagrado/manto-sagrado-api:manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/api/Dockerfile
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY
